Repository kmesh-net/website, pull requests merged in 2024-05, with the labels that each got.

#34 Changed the range of body text displayed on the page
  content/en/docs/community/membership.md
  themes/academic/assets/scss/academic/_docs.scss
Labels: size/XS, lgtm, approved

#36 add Notes of Writing Documentation in readme
  README.md
Labels: size/M, lgtm, approved

#31 fix broken photo link
  content/en/docs/architecture/architecture.md
  content/en/docs/performance/performance.md
  static/docs/architecture/kmesh-arch.svg
  static/docs/performance/fortio_performance_test.png
  static/docs/performance/perf_network.png
Labels: size/S, lgtm, approved

#32 add kmesh l7 content to user guide
  content/en/docs/userguide/try_waypoint.md
  content/en/docs/userguide/user-guide.md
  content/zh/docs/userguide/index.md
  content/zh/docs/userguide/try_waypoint.md
Labels: size/L, lgtm, approved

#39 add build Kmesh image guide
  content/en/docs/developer/_index.md
  content/en/docs/developer/build-guide.md
  content/en/docs/developer/index.md
Labels: size/L, lgtm, approved

#37 add authorization userguide
  content/en/docs/userguide/tcp_authorization.md
Labels: size/L, lgtm, approved

#40 docs(quickstart): should create namespace before apply yaml files
  content/en/docs/setup/quickstart.md
Labels: size/XS, lgtm, approved
