Repository kmesh-net/website, pull requests merged in 2024-09, with the labels that each got.

#70 path of the file to be check by code spell
  .github/workflows/main.yml
  content/en/docs/userguide/try_traffic_shifting.md
Labels: size/XS, lgtm, approved

#71 remove ns from Kmesh in cleanup of Install Waypoint
  content/en/docs/userguide/install_waypoint.md
Labels: size/XS, lgtm, approved

#72 Add Try Fault Injection Doc
  content/en/docs/userguide/install_waypoint.md
  content/en/docs/userguide/metric.md
  content/en/docs/userguide/service_metrics.md
  content/en/docs/userguide/try_fault_injection.md
  static/docs/user_guide/fault_injection1.png
  static/docs/user_guide/fault_injection2.png
Labels: size/L, lgtm, approved

#73 Add Try Request Timeouts Doc
  content/en/docs/userguide/request_routing_ads.md
  content/en/docs/userguide/traffic_shifting_ads.md
  content/en/docs/userguide/try_fault_injection.md
  content/en/docs/userguide/try_request_timeouts.md
  static/docs/user_guide/request_timeout1.png
  static/docs/user_guide/request_timeout2.png
Labels: size/L, lgtm, approved

#74 add demo
  content/en/docs/userguide/try_request_routing.md
  content/en/docs/userguide/try_traffic_shifting.md
Labels: size/S, lgtm, approved
