Repository kmesh-net/website, pull requests merged in 2024-08, with the labels that each got.

#66 add waypoint replacement note
  content/en/docs/userguide/install_waypoint.md
Labels: size/S, lgtm, approved

#62 add doc about how to use grafana to visualize service metrics
  content/en/docs/userguide/service_metrics.md
  content/en/docs/userguide/try_request_routing.md
  content/en/docs/userguide/try_traffic_shifting.md
  static/docs/userguide/grafana.png
Labels: size/M, lgtm, approved

#59 add documentation for Querying Metrics from Prometheus
  config/_default/config.toml
  content/en/blog/kmesh_introduce/index.md
  content/en/blog/kmesh_kubeconeu/index.md
  content/en/blog/sockmap_introduce/index.md
  content/en/docs/developer/build-guide.md
  content/en/docs/performance/performance.md
  content/en/docs/setup/quickstart.md
  content/en/docs/userguide/metric.md
  content/zh/blog/kmesh_introduce/index.md
  content/zh/blog/sockmap_introduce/index.md
  static/docs/userguide/metric/prometheus-graph.png
  static/docs/userguide/metric/prometheus-table.png
Labels: size/L, lgtm, approved

#68 update develop with kind
  content/en/docs/setup/develop_with_kind.md
Labels: size/XS, lgtm, approved
