Repository kmesh-net/website, pull requests merged in 2024-12, with the labels that each got.

#92 add LiZhenCheng9527 in approver
  OWNERS
Labels: size/XS, lgtm, approved

#85 Move quick start in front of develop doc
  content/en/docs/setup/quickstart.md
Labels: size/S, lgtm, approved

#87 Fix heading alignment
  content/en/docs/performance/resource_consumption.md
Labels: size/S, lgtm, approved

#90 [+]Locality LB user guide
  content/en/docs/userguide/locality_loadbalance.md
Labels: size/L, lgtm, approved

#97 add waypoint for deploy in asm tutorial
  content/en/blog/deploy_kmesh_in_asm/index.md
  content/zh/blog/deploy_kmesh_in_asm/index.md
Labels: size/M, lgtm, approved

#98 add documentation for visualizing traffic graph using Kiali under Kmesh
  content/en/docs/userguide/kiali.md
  static/docs/userguide/kiali.png
Labels: size/M, lgtm, approved

#100 add userguide for xdp_auth
  content/en/docs/userguide/xdp_auth.md
Labels: size/L, lgtm, approved

#101 fix: locality loadbalance doc
  content/en/docs/userguide/locality_loadbalance.md
Labels: size/S, lgtm, approved
