Repository kmesh-net/website, pull requests merged in 2024-10, with the labels that each got.

#80 change kmesh governance
  content/en/docs/community/contribute.md
  content/en/docs/community/governance.md
Labels: size/M, lgtm, approved

#81 Added reviewer role and removed owner
  content/en/docs/community/membership.md
  content/zh/docs/community/membership.md
Labels: size/M, lgtm, approved

#82 Delete obsolete document
  content/en/docs/developer/build.md
Labels: size/M, lgtm, approved

#83 user guide of kmeshctl
  content/en/docs/userguide/use_kmeshctl.md
Labels: size/L, lgtm, approved

#76 Add more video demo
  content/en/docs/userguide/install_waypoint.md
  content/en/docs/userguide/try_fault_injection.md
  content/en/docs/userguide/try_request_timeouts.md
Labels: size/S, lgtm, approved

#78 Update e2e-guide.md
  content/en/docs/developer/e2e-guide.md
Labels: size/M, lgtm, approved

#67 add resource consumption testing result
  content/en/docs/performance/resource_consumption.md
  content/zh/docs/performance/resource_consumption.md
  static/docs/performance/resource_test1.png
  static/docs/performance/resource_test2.png
  static/docs/performance/resource_test3.png
  static/docs/performance/resource_test_env.png
  static/docs/performance/resource_test_memory.png
  static/docs/performance/resource_test_result1.png
  static/docs/performance/resource_test_result2.png
  static/docs/performance/resource_test_result3.png
  static/docs/performance/resource_test_result4.png
Labels: size/L, lgtm, approved

#86 Add documentation for only installing istiod as a control plane
  content/en/docs/setup/quickstart.md
Labels: size/M, lgtm, approved

#77 Add Use Grafana to visualize kmesh perofrmance monitoring
  content/en/docs/userguide/performance_monitoring.md
  static/docs/userguide/kmesh_deamon_monitoring.jpg
  static/docs/userguide/kmesh_map_and_operation_monitoring.jpg
Labels: size/M, lgtm, approved
