Repository kmesh-net/website, pull requests merged in 2024-04, with the labels that each got.

#27 Update build doc
  content/en/docs/developer/index.md
Labels: size/XS, lgtm, approved

#28 add gitignore
  .gitignore
Labels: size/M, lgtm, approved

#19 add COD
  CODE_OF_CONDUCT.md
Labels: size/XS, lgtm, approved

#20 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, approved

#21 Improved readme.md of Kmesh Website
  README.md
Labels: size/S, lgtm, approved

#30 add quick start of kmesh
  content/en/docs/setup/quickstart.md
Labels: size/L, lgtm, approved

#33 fix link failed
  content/en/docs/_index.md
Labels: size/XS, lgtm, approved
