Repository kmesh-net/website, pull requests merged in 2024-07, with the labels that each got.

#52 use latest waypoint image without arch suffix
  content/en/docs/userguide/try_waypoint.md
Labels: size/XS, lgtm, approved

#48 Add e2e-test guide
  content/en/docs/developer/e2e-guide.md
Labels: size/M, lgtm, approved

#54 add document for enhanced kernel
  content/en/docs/setup/images/install_openEuler.png
  content/en/docs/setup/use_enhanced_kernel.md
Labels: size/M, lgtm, approved

#56 fix image display
  content/en/docs/setup/use_enhanced_kernel.md
Labels: size/XS, lgtm, approved

#53 add document for deploying and developing in kind
  content/en/docs/setup/develop_with_kind.md
  content/en/docs/setup/quickstart.md
Labels: size/L, lgtm, approved

#57 fix image display
  content/en/docs/setup/use_enhanced_kernel.md
  static/docs/setup/install_openEuler.png
Labels: size/XS, lgtm, approved

#58 remove unnecessary title
  content/en/docs/setup/develop_with_kind.md
Labels: size/XS, lgtm, approved

#60 add a bolg about kmesh join cncnf landscope
  content/en/blog/kmesh_join_cncf/images/architecture.png
  content/en/blog/kmesh_join_cncf/images/compare.png
  content/en/blog/kmesh_join_cncf/images/contribution.png
  content/en/blog/kmesh_join_cncf/images/introduce.png
  content/en/blog/kmesh_join_cncf/index.md
Labels: size/M, lgtm, approved

#63 polish tcp authorization user guide
  content/en/docs/userguide/tcp_authorization.md
Labels: size/S, lgtm, approved
