Repository kmesh-net/website, pull requests merged in 2025-03, with the labels that each got.

#150 [LFX-25] 01 - Update README to Reflect Docusaurus-Based Installation
  README.md
Labels: size/L, lgtm, approved

#153 [LFX-25] 02-Home page with welcome.md & CNCF joining blog
  .gitignore
  blog/authors.yml
  blog/kmesh-join-cncf/images/compare.png
  blog/kmesh-join-cncf/images/contribution.png
  blog/kmesh-join-cncf/images/introduce.png
  blog/kmesh-join-cncf/images/kmesh-arch.png
  blog/kmesh-join-cncf/index.md
  docs/setup/_category_.json
  docs/setup/develop-with-kind.md
  docs/setup/images/install_openEuler.png
  docs/setup/quick-start.md
  docs/setup/troubleshooting.md
  docs/setup/use-enhanced-kernel.md
  docs/welcome.md
  docusaurus.config.js
  netlify.toml
  package.json
  sidebars.js
  src/components/About/index.js
  src/components/About/styles.scss
  src/components/Blogs/index.js
  src/components/Blogs/styles.scss
  src/components/Supporters/index.js
  src/components/Supporters/index.scss
  src/components/Why/index.js
  src/components/Why/index.scss
  src/components/sectionContainer/index.js
  src/components/sectionContainer/styles.scss
  src/components/slider/index.js
  src/components/slider/index.scss
  src/css/custom.css
  src/pages/index.js
  src/plugins/blogGlobalData/index.js
  static/img/Kmesh-icon.png
  static/img/favicons/favicon.ico
  static/img/github.svg
  static/img/headers/bubbles-wide.jpg
  static/img/headers/star.png
  static/img/logo.png
  static/img/logo.svg
  static/img/slack.svg
  static/img/supporters/huawei.png
  static/img/supporters/openEuler.svg
  static/img/x.svg
  yarn.lock
Labels: lgtm, approved, size/XXL

#159 [LFX-25] 07- Kmesh v2 transport layer
  docs/transpot-layer/_category_.json
  docs/transpot-layer/images/grafana.png
  docs/transpot-layer/images/kmesh_deamon_monitoring.jpg
  docs/transpot-layer/images/kmesh_map_and_operation_monitoring.jpg
  docs/transpot-layer/images/prometheus-graph.png
  docs/transpot-layer/images/prometheus-table.png
  docs/transpot-layer/l4-metrics.md
  docs/transpot-layer/performace-monitoring.md
  docs/transpot-layer/service-metrics.md
  docs/transpot-layer/tcp-authorization.md
  docs/transpot-layer/xdp-auth.md
Labels: lgtm, approved, size/XL

#155 [LFX-25] 03 - developer guide documentation
  docs/developer-guide/Kmeshctl-usage/Kmesh Authz/ kmeshctl-authz-disable.md
  docs/developer-guide/Kmeshctl-usage/Kmesh Authz/_category_.json
  docs/developer-guide/Kmeshctl-usage/Kmesh Authz/kmeshctl-authz-enable.md
  docs/developer-guide/Kmeshctl-usage/Kmesh Authz/kmeshctl-authz-status.md
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/_category_.json
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/configuration.md
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/kmeshctl-waypoint-apply.md
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/kmeshctl-waypoint-delete.md
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/kmeshctl-waypoint-generate.md
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/kmeshctl-waypoint-list.md
  docs/developer-guide/Kmeshctl-usage/Kmesh waypoint/kmeshctl-waypoint-status.md
  docs/developer-guide/Kmeshctl-usage/_category_.json
  docs/developer-guide/Kmeshctl-usage/installation.md
  docs/developer-guide/Kmeshctl-usage/kmeshctl-accesslog.md
  docs/developer-guide/Kmeshctl-usage/kmeshctl-dump.md
  docs/developer-guide/Kmeshctl-usage/kmeshctl-log.md
  docs/developer-guide/Kmeshctl-usage/kmeshctl-secret.md
  docs/developer-guide/Kmeshctl-usage/kmeshctl-version.md
  docs/developer-guide/Tests/e2e-test.md
  docs/developer-guide/Tests/unit-test.md
  docs/developer-guide/_category_.json
  docs/developer-guide/build-guide.md
  docs/developer-guide/traffic-spilt.md
Labels: lgtm, approved, size/XL

#157 [LFX-25] 05 - performance documentation
  docs/performance/_category_.json
  docs/performance/images/fortio_performance_test.png
  docs/performance/images/perf_network.png
  docs/performance/images/resource_test1.png
  docs/performance/images/resource_test2.png
  docs/performance/images/resource_test3.png
  docs/performance/images/resource_test_env.png
  docs/performance/images/resource_test_memory.png
  docs/performance/images/resource_test_result1.png
  docs/performance/images/resource_test_result2.png
  docs/performance/images/resource_test_result3.png
  docs/performance/images/resource_test_result4.png
  docs/performance/performance.md
  docs/performance/resource-consumption.md
Labels: size/L, lgtm, approved

#158 [LFX-25] 06 - community documentation
  docs/community/_category_.json
  docs/community/contribute.md
  docs/community/feature-lifecycle.md
  docs/community/governance.md
  docs/community/membership.md
Labels: size/L, lgtm, approved

#160 [LFX-25] 08- Kmesh v2 application layer
  docs/application-layer/_category_.json
  docs/application-layer/images/fault_injection1.png
  docs/application-layer/images/fault_injection2.png
  docs/application-layer/images/kiali.png
  docs/application-layer/images/request_routing1.png
  docs/application-layer/images/request_routing2.png
  docs/application-layer/images/request_timeout1.png
  docs/application-layer/images/request_timeout2.png
  docs/application-layer/install_waypoint.md
  docs/application-layer/kiali.md
  docs/application-layer/locality-loadbalance.md
  docs/application-layer/request-routing-ads.md
  docs/application-layer/traffic-shifting-ads.md
  docs/application-layer/try-fault-injection.md
  docs/application-layer/try-request-routing.md
  docs/application-layer/try-request-timeout.md
  docs/application-layer/try-traffic-shifting.md
  docs/setup/develop-with-kind.md
  docs/setup/use-enhanced-kernel.md
  src/css/custom.css
Labels: lgtm, approved, size/XXL

#161 Spell checking can also be performed in the change-theme branch
  .github/workflows/main.yml
Labels: size/XS, lgtm, approved

#162 [LFX-25] 09 - Kmesh v2 blogs migrations
  blog/authors.yml
  blog/deploy-kmesh-in-asm/images/kmesh-arch.png
  blog/deploy-kmesh-in-asm/index.md
  blog/kmesh-join-cncf/index.md
  blog/kmesh-observability/images/probe.png
  blog/kmesh-observability/index.md
  blog/kmesh_introduce/images/istio-arch.png
  blog/kmesh_introduce/images/istio-kmesh-datapath-compare.png
  blog/kmesh_introduce/images/istio-perf-analysis.png
  blog/kmesh_introduce/images/istio-performance.png
  blog/kmesh_introduce/images/kmesh-arch.png
  blog/kmesh_introduce/images/kmesh-performance.png
  blog/kmesh_introduce/images/servicemesh-evolution.png
  blog/kmesh_introduce/images/sockmap-performance.png
  blog/kmesh_introduce/images/sockmap.png
  blog/kmesh_introduce/index.md
  blog/kmesh_kubeconeu/images/kmesh-arch.png
  blog/kmesh_kubeconeu/images/kmesh-bpf-tailcall.png
  blog/kmesh_kubeconeu/images/kmesh-comp.png
  blog/kmesh_kubeconeu/images/kmesh-kubecon-europe.png
  blog/kmesh_kubeconeu/images/kmesh-map-in-map.png
  blog/kmesh_kubeconeu/images/kmesh-orch.png
  blog/kmesh_kubeconeu/images/kmesh-perf-cpu.png
  blog/kmesh_kubeconeu/images/kmesh-perf-latency.png
  blog/kmesh_kubeconeu/images/kmesh-xds.png
  blog/kmesh_kubeconeu/index.md
  blog/sockmap-itroduce/images/1.png
  blog/sockmap-itroduce/images/2.png
  blog/sockmap-itroduce/images/3.png
  blog/sockmap-itroduce/images/4.png
  blog/sockmap-itroduce/images/5.png
  blog/sockmap-itroduce/images/6.png
  blog/sockmap-itroduce/images/7.png
  blog/sockmap-itroduce/index.md
  docs/application-layer/_category_.json
  docs/community/_category_.json
  docs/developer-guide/_category_.json
  docs/transpot-layer/_category_.json
Labels: lgtm, approved, size/XL
