Repository kmesh-net/website, pull requests merged in 2025-08, with the labels that each got.

#211 change website footer
  docusaurus.config.js
  i18n/zh/docusaurus-theme-classic/footer.json
Labels: size/XS, lgtm, approved

#212 docs: Add OCI Helm installation instructions
  docs/setup/quick-start.md
Labels: size/S, lgtm, approved

#215 docs: improve versioned Helm chart installation
  docs/setup/quick-start.md
Labels: size/S, lgtm, approved

#218 add new trackingID
  docusaurus.config.js
Labels: size/XS, lgtm, approved

#219 new trackingID
  docusaurus.config.js
Labels: size/XS, lgtm, approved

#221 did(info): added community meeting information
  docs/community/contribute.md
  yarn.lock
Labels: lgtm, approved, size/XXL

#226 ipsec: modified ipsec user guide, update kmeshctl-secret.md
  docs/developer-guide/Kmeshctl-usage/kmeshctl-secret.md
Labels: size/M, lgtm, approved
