Repository kmesh-net/website, pull requests merged in 2025-02, with the labels that each got.

#125 automate fetch current year in footer section
  config/_default/config.toml
Labels: size/XS, lgtm, approved

#121 [resolved issue #118] enable the light & dark mode
  config/_default/params.toml
Labels: size/XS, lgtm, approved

#128 [Feat]:Add Supported Observability Tools section
  content/en/docs/performance/performance.md
Labels: size/S, lgtm, approved

#120 card component modifications
  themes/academic/assets/scss/academic/_card.scss
  themes/academic/layouts/_default/list.html
Labels: size/S, lgtm, approved

#119 Update README.md
  README.md
Labels: size/M, lgtm, approved

#122 Updated the Font Awesome CDN version and twitter logo
  config/_default/languages.toml
  config/_default/menus.toml
  themes/academic/data/assets.toml
Labels: size/S, lgtm, approved

#134 two time of blog title removed and make once
  content/en/blog/deploy_kmesh_in_asm/index.md
Labels: size/XS, lgtm, approved

#132 docs: Update architecture page with component details
  content/en/docs/architecture/architecture.md
Labels: size/M, lgtm, approved

#135 [docs] : implement a clearer value proposition for Kmesh
  content/en/docs/_index.md
Labels: size/S, lgtm, approved

#130 docs: Add installation troubleshooting guide
  content/en/docs/setup/troubleshooting.md
Labels: size/L, lgtm, approved

#136 [docs]:Added clearer prerequisites and verification steps
  content/en/docs/setup/quickstart.md
Labels: size/M, lgtm, approved

#137 navbar ui modification
  .gitignore
  themes/academic/assets/scss/academic/_nav.scss
  themes/academic/layouts/partials/navbar.html
Labels: size/M, lgtm, approved

#142 Fix sidebar confusion on doc pages
  config/_default/menus.toml
Labels: size/XS, lgtm, approved

#96 add kernel-native mode startup
  content/en/docs/setup/quickstart.md
Labels: size/S, lgtm, approved

#49 add load balance userguide
  content/en/docs/userguide/load_balancing.md
Labels: size/L, lgtm, approved

#143 modify file name
  content/en/docs/userguide/load_balancing.md
Labels: size/XS, lgtm, approved

#141 [doc]: created concepts page
  config/_default/menus.toml
  content/en/docs/concepts/_index.md
  content/en/docs/concepts/concepts.md
Labels: size/L, lgtm, approved

#129 perf: Improve website performance and Lighthouse score
  README.md
  content/en/docs/performance/performance.md
Labels: size/S, lgtm, approved

#107 Updating the download address of the kmeshctl installation documentation
  content/en/docs/userguide/use_kmeshctl.md
Labels: size/XS, lgtm, approved
